### ISSUE TITLE
command-line mode ?

### ISSUE THREAD

**Issue by VitoYane** [IgorMundstein/WinMemoryCleaner#15]
This tool is incredibly useful, as it has reduced my memory usage by nearly 30%. However, does it support command-line mode so that I can schedule it to run periodically using task scheduler instead of having it run constantly in memory?

Regarding the UI, currently the minimize function only minimizes to the taskbar, and clicking the close button will exit the program directly. I would like to request that the minimize function be updated to minimize to the system tray instead, in order to free up space on the taskbar.
![image](https://user-images.githubusercontent.com/17432059/228710435-5d742a42-5b94-4fb9-b8c2-e50af2f85075.png)

**Comment by IgorMundstein** [comment]
> This tool is incredibly useful, as it has reduced my memory usage by nearly 30%. However, does it support command-line mode so that I can schedule it to run periodically using task scheduler instead of having it run constantly in memory?

https://github.com/IgorMundstein/WinMemoryCleaner#%EF%B8%8F-command-arguments-no-gui

Add the task calling the executable with the memory areas you want to optimize as parameters.
Example: `WinMemoryCleaner.exe /ModifiedPageList /ProcessesWorkingSet /StandbyList /SystemWorkingSet`

> Regarding the UI, currently the minimize function only minimizes to the taskbar, and clicking the close button will exit the program directly. I would like to request that the minimize function be updated to minimize to the system tray instead, in order to free up space on the taskbar.

https://github.com/IgorMundstein/WinMemoryCleaner#settings

Just enable the setting: `Minimize to the tray when closed` - Minimize the app to the system tray when clicking the close (X) button.

Then click on X, and it will be minimized to system tray instead of closing the app.

**Comment by VitoYane** [comment]
it works, thank you !
