### ISSUE TITLE
Windows error msg popup when opening 2.1

### ISSUE THREAD

**Issue by Slluxx** [IgorMundstein/WinMemoryCleaner#26]
Just opening WMC 2.1 throws this windows message popup:

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/15162905/59724d8b-bf30-4028-a2e9-2ed0bc2d36b8)

Here is a [stackoverflow question](https://stackoverflow.com/questions/19295233/uiautomation-invokepattern-throws-hotkey-already-registered-exception) so you know what it translates to and (maybe) whats causing it. The program continues after clicking okay so its not too big of a deal.

I also got this message once on trying to start, but cant remember if WMC continued afterwards. 
It translates to `The resource with the name "DarkBackground" could not be found.`
I could only produce this once however so it might be some windows glitch that didn't allow me to use the resources of this application because it was already in use or whatever, not entirely sure.
![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/15162905/8190bc53-5e7c-4e62-859c-fbeb9849e6e8)

**Comment by IgorMundstein** [comment]
These errors happen due to conflicts between the old and new versions when updated. Probably, some app process got stuck by the Windows. I've been using an older version of the .NET framework for compatibility with older Windows, making implementing features already existing in newer frameworks challenging. I have to create some existing features in more recent versions from scratch.

Anyway. I applied a workaround for the first error, which will disappear on the next version because it's persistent. The second error should've yet to appear. It's complaining about a background color not being found and should not be continuous.

**Comment by Slluxx** [comment]
Yeah, i thought so. Compatibility always sucks.

Sounds good to me though, and i doubt that the second error is a serious issue, as i was only able to get it once after messing around with WMC because of the first error and never again. Just wanted to report it anyway.

I guess it can be closed if you already have a workaround :)

**Comment by IgorMundstein** [comment]
It's all good. I already fixed it for the 2.2 version.

I am just working on UI to make all controls rounded and dark-ish. It's been painful because I don't have some framework features, and I don't want to use thrid-libraries because they will generate DLL files alongside the executable. I like to have just the .exe without other files like "portable mode."

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/40e2634e-ba8b-4ca4-99d0-23d445443868)

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/5833882a-2d1e-4a5e-a079-551e3a7443b7)

**Comment by Slluxx** [comment]
> [...] because they will generate DLL files alongside the executable

you can always embed dll files inside executables if thats your concern. ([Single-file deployment](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#publish-a-single-file-app---sample-project-file), [IncludeAllContentForSelfExtract](https://stackoverflow.com/a/72957910/5413081), [ilmerge](https://github.com/dotnet/ILMerge), [boxeapp](https://www.boxedapp.com/) and many more).

If you would be down to rewrite the app in C++, there is ImGUI, which is a **fantastic** ui library that works basically everywhere. And a release build of IMGUI alone is just 500kb with no extra DLLs. By default it may look slightly "deverloper/debug ish" but people have created awesome guis with it, as it is just so good.

Also, what the fuck, who has 52 GB ram lmao

**Comment by IgorMundstein** [comment]
> > [...] because they will generate DLL files alongside the executable
> 
> you can always embed dll files inside executables if thats your concern. ([Single-file deployment](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#publish-a-single-file-app---sample-project-file), [IncludeAllContentForSelfExtract](https://stackoverflow.com/a/72957910/5413081), [ilmerge](https://github.com/dotnet/ILMerge), [boxeapp](https://www.boxedapp.com/) and many more).

Well. That might not work with the current .NET framework that I use, and it's hard to guarantee it will work on all Windows versions. Also, it might add extra steps to build or stop working suddenly.

I am using a few Windows libraries and it's easy to build.

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/3da60dec-257a-4e29-8e7f-09648f21c6ad)

> If you would be down to rewrite the app in C++, there is ImGUI, which is a **fantastic** ui library that works basically everywhere. And a release build of IMGUI alone is just 500kb with no extra DLLs. By default it may look slightly "deverloper/debug ish" but people have created awesome guis with it, as it is just so good. (Python has DearPyGUI and there are probably C# bindings too)

.NET has so many UI features. The limitation is supporting old Windows versions. Windows XP was released on October 25, 2001. C++ is awesome but not my expertise.

> Also, what the fuck, who has 52 GB ram lmao

I know. Windows doesn't even use it, but I built my desktop computer and RAM (DDR5) is cheap here. Sometimes, there is no 32 GB available to buy.
