### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by hugok79** [IgorMundstein/WinMemoryCleaner#33]
The **Portuguese** translation is in **Brazilian Portuguese** or **Portuguese (Brazil)**. Can I create a PR to replace the **Portuguese.JSON** file with the correct translation of Portuguese sponken in Portugal **Portuguese (Portugal)** and rename the other file to **Portuguese (Brazil)** or **BrazilianPortuguese.JSON** ?

https://ss64.com/locale.html

LCID  -  Name  - DisplayName
2070  - pt-PT   - Português (Portugal)
1046  - pt-BR   - Portuguese (Brazil)

**Comment by hugok79** [comment]
We Portuguese understand, it is simply that the Portuguese spoken in Portugal is the most appropriate.

**Comment by IgorMundstein** [comment]
It's natural for a language to evolve. Even English has new "invented" words. Many languages ​​died because they stopped in time.

Brazil has a larger population (200 million) than Portugal (10 million), with many native speakers, impacting content availability. It's like the USA and Britain. Mexico and Spanish.

It is not intelligent to maintain software with each dialect variation if it is insignificant. The Google translator translates to Brazillian Portuguese when the user selects Portuguese. Thus, Portuguese (BR) is the preferred one.

**Comment by hugok79** [comment]
That's why I don't use google Translator !!! I prefer to use **DeepL** https://www.deepl.com/translator

Although I also sometimes use an automatic translator to be faster, every translation I do is always checked

https://en.wikipedia.org/wiki/Portuguese_Language_Orthographic_Agreement_of_1990
