### ISSUE TITLE
Free RAM on trayicon ?

### ISSUE THREAD

**Issue by foxy999** [IgorMundstein/WinMemoryCleaner#37]
Would be really nice to display the free RAM on the trayicon on Windows without having to hover over the icon

**Comment by IgorMundstein** [comment]
Thanks for the suggestion. I hope the app is useful. I am aware of other similar apps that have this feature. I'll keep this enhancement in mind. 👍

**Comment by Happygolucky254** [comment]
I know other apps have this ... rather than create a new suggestion or hop on this one. I most used this app on demand from the hidden tray and while a number might be nice, I would only need the result of the optimize. e.g if I run the optimize from the right click and the system tray container disappears, we only get a toast message confirming 'Memory Optimized', it would be nice if it said 'Memory Optimized : % Free' that would be better as I don't actually see the number on the icon unless I am already opening the show hidden icons.

**Comment by IgorMundstein** [comment]
> I know other apps have this ... rather than create a new suggestion or hop on this one. I mostly use this app on demand from the hidden tray and while a number might be nice, I would only need the result of the optimize. e.g if I run the optimize from the right click and the system tray container disappears, we only get a toast message confirming 'Memory Optimized', it would be nice if it said 'Memory Optimized : % Free' that would be better as I don't actually see the number on the icon unless I am already opening the show hidden icons.

Some operations run asynchronously. After the optimization, Windows will still reallocate the memory—this period is variable based on the amount of process and hardware specs. So, any similar app that shows stats is inaccurate, and it provides a false value to the user. I don't like it, so I chose not to implement it.

**Comment by Happygolucky254** [comment]
I don't doubt what you saying, I don't know how it works. I'm sure it takes a while to settle, like if I hover over the icon there is a toast for the used ram so that is why a number is not exactly essential to be there for me. I was only saying in the event that the hidden icon are not visible and you can't hover, when the toast comes after an optimize it can save checking who want to ... I know technically looking at it seem useless cause it's only going to recover what it can recover anyway but some indicator might not hurt so those of us who run on demand ... you could change your icon to a circle swapping the colors like a temperature meter blue green yellow red and split in in 8 or 16 icons and display one relative to the estimated or actual results .. so when I open my hidden icons I can see it up at amber, I can run it on demand from the right click and when I continue doing my work, when the toast comes 'Memory Optimized' the icon displays unbidden for a time and I can see if it change to green ... just an idea

**Comment by IgorMundstein** [comment]
> I don't doubt what you saying, I don't know how it works. I'm sure it takes a while to settle, like if I hover over the icon there is a toast for the used ram so that is why a number is not exactly essential to be there for me. I was only saying in the event that the hidden icon are not visible and you can't hover, when the toast comes after an optimize it can save checking who'd like to ... I know technically looking at it seem useless cause it's only going to recover what it can recover anyway but some indicator might not hurt so those of us who run on demand ... you could change your icon to a circle swapping the colors like a temperature meter blue green yellow red and split in in 8 or 16 icons and display one relative to the estimated or actual results .. so when I open my hidden icons I can see it up at amber, I can run it on demand from the right click and when I continue doing my work, when the toast comes 'Memory Optimized' the icon displays unbidden for a time and I can see if it change to green ... just an idea  

Sure. It doesn't hurt adding more info, even if it's not 100% accurate. I am thinking about including more features as suggested. I already have some stuff in mind. I know it looks simple, but this app is stable and has good features. I have other projects to take care of. However, thanks for the suggestions. It is an incentive for me to keep upgrading this free application.

**Comment by Happygolucky254** [comment]
Sorry, for bombarding you with message, I'll stop now lol. I know it's not as easy as it looks ,but when I imagine what I thinking, it would look something the following, in most cases I would think there would be substance to the icon for most users.

https://www.istockphoto.com/fr/vectoriel/fl%C3%A8ches-gm474520830-65393565?phrase=circle+arrow

**Comment by IgorMundstein** [comment]
> Sorry, for bombarding you with message, I'll stop now lol. I know it's not as easy as it looks ,but when I imagine what I thinking, it would look something like the following, in most cases I would think there would be substance to the icon for most users while displaying a relative number of arrows close to being used .
> 
> https://www.istockphoto.com/fr/vectoriel/fl%C3%A8ches-gm474520830-65393565?phrase=circle+arrow

That's an idea. The biggest challenge is to make 16x16 icons visible. They are so small. The OP idea is to show numbers instead of the icon. Again, nothing new. Other apps do it.

**Comment by IgorMundstein** [comment]
Added to version [2.6](https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.6)
