### ISSUE TITLE
Freezes when cleaning memory?

### ISSUE THREAD

**Issue by Sayrix** [IgorMundstein/WinMemoryCleaner#39]
Hello when the software is cleaning my memory, my pc is completely freezing for ~2 minutes and then I receive the notification that my memory was cleaned, I am on Windows 11 and I use the latest version of the software, If you need any more informations or logs say it to me

**Comment by IgorMundstein** [comment]
Two minutes to optimize everything, and how much memory did you recover? 

The application uses Windows functions to clean the memory. The optimization speed will depend on your computer's hardware.  For example, Windows uses your hard drive for paging. If you have an SSD instead of an HDD, this time reduces significantly. 

You can try selecting memory areas individually and see which one is taking longer to optimize. Based on the cost time X benefit of recovered memory, you decide which memory area to optimize. Does it make sense?

If you want to dig deeper into memory analysis. I recommend this tool: [RAMMap](https://learn.microsoft.com/en-us/sysinternals/downloads/rammap)

**Comment by Sayrix** [comment]
Maybe not 2 mins something like between 1 and 2 mins and I save ~10% memory and I have 16GB of ram but the problem is not that it takes time it's that it makes my pc lagging when cleaning the memory and btw I setup my swap on my HDD to don't f*** my ssd wearout

**Comment by IgorMundstein** [comment]
That might be your issue. I know SSD is expensive, but it's faster. Try switching back the swap to SSD to see if the optimization changes by chance. Don't forget to restart the Windows after. As I said, select one memory area by time and run some tests. Also, open the task manager and check if the disk or CPU utilization reaches 100%. That will tell what hardware component is lagging your pc. Feel free to post some results. 👍

**Comment by Sayrix** [comment]
I've just looked and when I clean my memory my hdd is at 100% and my windows lags, and when my hdd is below 100% my windows no longer lags but how can I make it so that it no longer lags, perhaps limit disk usage when cleaning?

**Comment by Sayrix** [comment]
I can't afford to use my ssd for swap, it'll really kill it and I wouldn't recommend it to anyone if it's a ssd where your windows and lots of other things are also present, but if it's a dedicated ssd for swap, why not

**Comment by IgorMundstein** [comment]
I understand hardware might be expensive, but it's made to be used. It's like buying a new car a keep it in the garage because you want to save tires, for example.

The app only calls Windows native memory functions. Unfortunately, I cannot control how Windows will use your computer resources to run these functions.

My PC takes 2 seconds to run the optimization. So, it is hard for me to replicate your scenario.

I am interested to know if you use the SSD to swap; the Windows won't freeze. Can you run this test?

Also, can you try a different priority process? Change the WinMemoryCleaner.exe process priority to low, and let's see if Windows will allocate fewer resources. Or even high/real-time to see if it speeds up the freeze time.

Here is an article on how to change a process priority: https://winaero.com/change-process-priority-windows-10/amp/

**Comment by IgorMundstein** [comment]
@Sayrix 

Please, run this build and let me know if something has changed about the freezing.
[WinMemoryCleaner.zip](https://github.com/IgorMundstein/WinMemoryCleaner/files/12326162/WinMemoryCleaner.zip)

**CHANGES**

- **I set the app process and threads to low priority.**

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/e39727e8-cfc1-4096-971d-b4a1ed13dfde)

- **The log now shows the elapsed time for each memory area.**

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/a1d985ec-f119-4f12-bdd0-76671cb2d66d)

**Comment by Sayrix** [comment]
![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/43046854/f76c42d6-4e63-46c8-8c8d-3bce91668d60)
It took less time, maybe because i just started my computer, i will try later

**Comment by IgorMundstein** [comment]
Well, **10.6 seconds** is far from **2 minutes**. I don't think setting the priority to low reduces it. It should increase the time.

How about the freezing? How is your HDD? Did you switch to SSD?

Keep using it, and let me know. I need more details about what were your software/hardware changes. You can click on the tab "General"; it will provide a better view format, as seen in my image.

**Comment by Sayrix** [comment]
Yeah, it seems to be better, i still use my hdd btw

**Comment by Sayrix** [comment]
![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/43046854/3cda1a59-f295-47bf-a07f-af2bc19f0cc3)

**Comment by IgorMundstein** [comment]
Nice.

Does it still freeze?

**Comment by Sayrix** [comment]
A little bit but less

**Comment by IgorMundstein** [comment]
Improved in version [2.5](https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.5)
