### ISSUE TITLE
Can it be minimized？

### ISSUE THREAD

**Issue by imzhoukunqiang** [IgorMundstein/WinMemoryCleaner#5]
Hi , Thanks for the tool, it's very helpful for me.

The tool always on the top,it is possible to minimized?

**Comment by IgorMundstein** [comment]
Hi, thanks for the feedback.

The always on the top property was set because there are no benefits to keeping the window open. The idea is to open, clean, and close. I am working on version 2.0, which will include an auto-clean function, and consequently, the always on the top will have to be set to false.

**Comment by imzhoukunqiang** [comment]
Thank you very much, very excited about the version 2.0. Auto-clean is a awesome idea!

**Comment by IgorMundstein** [comment]
Added.

Download the 2.0 version: https://github.com/IgorMundstein/WinMemoryCleaner/releases/latest/download/WinMemoryCleaner.exe
