### ISSUE TITLE
Running Program

### ISSUE THREAD

**Issue by rtxryzen** [IgorMundstein/WinMemoryCleaner#53]
### Checklist

- [X] I have used the search function to see if someone else has submitted the same bug report.
- [X] I will describe the problem in as much detail as possible.

### App version

2.5

### Windows version

11

### Steps To Reproduce

at run the file 
and show the some bar i'm click yes

### Current Behavior

Can't run the .exe file
Not show in Task Manager

**Comment by IgorMundstein** [comment]
Sorry, but I didn't get the issue. 🤔

Please clarify it with more detailed information and screenshots.

**Comment by breakTBB** [comment]
> Sorry, but I didn't get the issue. 🤔
> 
> Please clarify it with more detailed information and screenshots.

I roughly understand that he may be running the .exe file, but it could be due to system security policies (such as UAC) or his anti-malware software prohibiting the execution. 
If he is not a native English speaker, he should at least check using translation software. 
He should also provide a screenshot of the issue.
