### ISSUE TITLE
Auto memory cleaning

### ISSUE THREAD

**Issue by ShatteredGod** [IgorMundstein/WinMemoryCleaner#6]
Will there be a feature to auto clean the ram after a certain amount of time? like, have it always open in the background or minimized and do its thing. i think it'd be cool for users who open programs and play games all the time.

**Comment by IgorMundstein** [comment]
I just I've been pretty busy. I was curious to know if anyone was using it or waiting for updates, but suddenly I started receiving messages asking for an update.

**Comment by ShatteredGod** [comment]
> HI @ShatteredGod
> 
> I just I've been pretty busy. I was curious to know if anyone was using it or waiting for updates, but suddenly I started receiving messages asking for an update.
> 
> I'll dedicate some time to it in the following weeks.

Thank you for the response! I will look forward for the update ^^

**Comment by wixaw** [comment]
Hello @IgorMundstein 
Great update! ❤️ 
However, to improve my use in video games, I would like to be able to automate the cleaning function every 5 or 10 minutes, for example. 
Thank you in advance
William.

**Comment by IgorMundstein** [comment]
> Hello @IgorMundstein 
> Great update! ❤️ 
> However, to improve my use of video games, I would like to be able to automate the cleaning function every 5 or 10 minutes, for example. 
> Thank you in advance
> William.
> 

I do not recommend running every minute. That's why I set a minimum of 1 hour.

However, there is a way to turn on an "aggressive mode". If you set it to auto-optimize when memory free is below 100%, it will run every 5 minutes (delay between this optimization) because it will never reach 100% of free memory. I do recommend a test of it when playing, as well check and uncheck some memory areas to analyze performance and stability. Every game/hardware is different.

Lemme know your results and I can think about changing the setting to minutes. 👍

**Comment by wixaw** [comment]
I haven't tried it yet on my wife old gaming PC which has very few resources,
But on the work tablet (Surface go) which is super slow, it does the job well when I put it on below 100%, without crash ( i use thunderbird, onenote and chrome) 
I use your software on all my pc now, and I even have memory leaks on a server application, I planned to use it on it to correct my problem since the editor does not do the job. Thank's you
