### ISSUE TITLE
Firewall blocked behaviour

### ISSUE THREAD

**Issue by porkmanager** [IgorMundstein/WinMemoryCleaner#66]
### Checklist

- [X] I have used the search function to see if someone else has submitted the same bug report.
- [X] I will describe the problem in as much detail as possible.

### App version

last one

### Windows version

11 22631.2861

### Steps To Reproduce

On starting program happens when software connection is blocked by the firewall
![ss](https://github.com/IgorMundstein/WinMemoryCleaner/assets/44921055/5385f193-746c-4aa8-bd00-986c1c30edcd)

### Current Behavior

![ss](https://github.com/IgorMundstein/WinMemoryCleaner/assets/44921055/5385f193-746c-4aa8-bd00-986c1c30edcd)

**Comment by IgorMundstein** [comment]
The app only connects to GitHub to check for updates. My Windows Firewall never blocked it.

I'll try to reproduce it, but if the firewall blocks any app, it won't work. It's up to the user to handle it.

Would anybody be able to give more details? For example, the error message doesn't appear if the auto-update setting is disabled.

**Comment by IgorMundstein** [comment]
I couldn't reproduce the issue. It might be a temporary one because of the version update. 

Have you re-opened the app? Could you let me know if the error continues?

Can you access the Windows Registry and delete the app entries?
Path: Computer\HKEY_CURRENT_USER\Software\WinMemoryCleaner

![image](https://github.com/IgorMundstein/WinMemoryCleaner/assets/3512138/30f93215-61aa-4d6b-9849-770a02ab9acf)

**Comment by W130SN** [comment]
Since yesterday, Windows Security has quarantined the program.
When trying to download today, Windows Smart Screen blocks the download.

![virus1](https://github.com/IgorMundstein/WinMemoryCleaner/assets/59985716/0e6e079a-b4be-45f9-9772-dc7b6d14e56d)
![virus](https://github.com/IgorMundstein/WinMemoryCleaner/assets/59985716/530d3122-603e-4d63-aed6-8363c822ad05)
![Untitled](https://github.com/IgorMundstein/WinMemoryCleaner/assets/59985716/45c298a5-be02-426a-b109-5a7f77b21be1)

**Comment by porkmanager** [comment]
> Blocking by WFP.

I tried another fw tricks to check that. Any another blocking rules like windows firewall or add IP to the windows hosts file doesnt crashing WinMemoryCleaner, ctd happens only when its blocking by the windows filtering platform.

**Comment by IgorMundstein** [comment]
I understand, but that's not the app's fault. It's trying to connect to GitHub to check for updates because the setting is enabled, and you click to block the connection. You are forcing an error, and it's popping up a message.

What do you expect the app to do?

If you don't want the app connecting to GitHub, just turn off the auto-update.

**Comment by porkmanager** [comment]
> What do you expect the app to do?

Im using WFP as my major windows firewall filter like 10y, its never caused any troubles with apps, this was first time. I expect that app can runs normally when it cant get connect to the server like another apps. 
I understand how WinMemoryCleaner cleaner works and understand that is connecting to github for the update. Its np for me, im just disabled autoupd. and continue to use it. Just reported this bug.

**Comment by Mannard** [comment]
Happened to me as well,  if the app can't check for updates (firewall) it errors.   (Windows 11, MWB Wfc)
![ksnip_20231221-154205](https://github.com/IgorMundstein/WinMemoryCleaner/assets/68917397/18b04245-3807-4d9e-ab08-76d161c76fcd)

**Comment by IgorMundstein** [comment]
Improved on version [2.7](https://github.com/IgorMundstein/WinMemoryCleaner/releases/tag/2.7)
